### ISSUE TITLE
Upgrade to android studio project

### ISSUE THREAD

**Issue by deepankarb** [deepankarb/Pingr#2]
Currently this is an eclipse project. Upgrade to android studio project. Without using android studio further development is not possible.

**Comment by deepankarb** [comment]
@DevB007 have you forked the repo?

**Comment by DevB007** [comment]
Yes, I did.

**Comment by deepankarb** [comment]
Cool. Were you able to import the project into studio?

**Comment by DevB007** [comment]
Yes. Its working. Pushing now.
